### ISSUE TITLE
Link to Documentation from README is broken

### ISSUE THREAD

**Issue by RaoOfPhysics** [inveniosoftware/invenio-orcid#10]
http://pythonhosted.org/invenio-orcid/ gives a 404 page.

Can fix if provided with the right link or can remove if no documentation exists. Please let me know.

Re-pinging @lnielsen, @jirikuncar and @tiborsimko.

(Original issue erroneously opened here: https://github.com/inveniosoftware/invenio-pages/issues/36)

**Comment by lnielsen** [comment]
It's because no release have been made on PyPI yet. Once we release, it automatically builds the latest version of the documentation and uploads it to Pythonhosted.

**Comment by RaoOfPhysics** [comment]
So, should the link be removed for now and then added when the release is available on PyPI?

**Comment by lnielsen** [comment]
No, we just leave it since it will eventually work as soon as invenio-orcid is in a usable state and if we remove it, then we probably forget to add it later.
